version: '3.8'

services:
  app:
    build: .
    container_name: dj-jagger-cms
    restart: unless-stopped
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./public:/app/public # To allow live edits without rebuilds for frontend
    environment:
      - NODE_ENV=production
