#!/bin/bash
set -u

# Styling colors
GREEN='\033[1;32m'
BLUE='\033[1;34m'
RED='\033[1;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}======================================${NC}"
echo -e "${BLUE}         CMS.v2 - INSTALLER           ${NC}"
echo -e "${BLUE}======================================${NC}"
echo ""

# Function to prompt with a default value
prompt() {
    local prompt_text=$1
    local default_value=$2
    local variable_name=$3

    read -r -p "$prompt_text [$default_value]: " input
    if [ -z "$input" ]; then
        declare -g "$variable_name=$default_value"
    else
        declare -g "$variable_name=$input"
    fi
}

# Escape a value so it can safely live inside double quotes in the .env file
# (backslashes and double quotes would otherwise break parsing).
esc() {
    printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

# Generate a random secret without requiring openssl.
gen_secret() {
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex 32
    else
        head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'
    fi
}

echo -e "${GREEN}--- 1. Server Configuration ---${NC}"
prompt "Port for the Webserver" "3000" PORT
prompt "Behind a TLS reverse proxy? (1 = yes, 0 = no)" "0" TRUST_PROXY
echo ""

echo -e "${GREEN}--- 2. Admin Login Setup ---${NC}"
prompt "Admin Username" "admin" ADMIN_USER
read -r -s -p "Admin Password (empty = generate a random one on first start): " ADMIN_PASS
echo ""
echo ""

echo -e "${GREEN}--- 3. Site Branding (editable later in the admin panel) ---${NC}"
prompt "Site name" "My CMS" SITE_NAME
prompt "Tagline" "A flexible, content-managed website" SITE_TAGLINE
prompt "Public site URL (for SEO/sitemap, e.g. https://example.com)" "" SITE_URL
echo ""

echo -e "${GREEN}--- 4. SMTP Configuration (optional, leave host empty to skip) ---${NC}"
prompt "SMTP Host (empty = disable email)" "" SMTP_HOST
if [ -n "$SMTP_HOST" ]; then
    prompt "SMTP Port" "587" SMTP_PORT
    prompt "SMTP Username / Auth Email" "noreply@example.com" SMTP_USER
    read -r -s -p "SMTP Password: " SMTP_PASS
    echo ""
    echo ""
    prompt "Sender Address ('From')" "'$SITE_NAME' <noreply@example.com>" SMTP_FROM
    prompt "Recipient Address ('To')" "inbox@example.com" SMTP_TO
else
    SMTP_PORT="587"; SMTP_USER=""; SMTP_PASS=""; SMTP_FROM=""; SMTP_TO=""
fi
echo ""

SESSION_SECRET=$(gen_secret)

echo -e "${BLUE}Generating .env file...${NC}"

cat > .env <<EOL
# Server Configuration
PORT=$PORT
TRUST_PROXY=$TRUST_PROXY

# Session secret (generated by install.sh)
SESSION_SECRET="$(esc "$SESSION_SECRET")"

# Admin account (created on first start)
ADMIN_USER="$(esc "$ADMIN_USER")"
ADMIN_PASS="$(esc "$ADMIN_PASS")"

# Site branding
SITE_NAME="$(esc "$SITE_NAME")"
SITE_TAGLINE="$(esc "$SITE_TAGLINE")"
SITE_URL="$(esc "$SITE_URL")"

# SMTP Configuration
SMTP_HOST="$(esc "$SMTP_HOST")"
SMTP_PORT=$SMTP_PORT
SMTP_USER="$(esc "$SMTP_USER")"
SMTP_PASS="$(esc "$SMTP_PASS")"
SMTP_FROM="$(esc "$SMTP_FROM")"
SMTP_TO="$(esc "$SMTP_TO")"
EOL

chmod 600 .env
echo -e "${GREEN}Success! .env file has been created (permissions 600).${NC}"

# The container runs as the unprivileged "node" user (uid 1000); make sure
# the data volume is writable for it.
mkdir -p data
if command -v chown >/dev/null 2>&1; then
    chown -R 1000:1000 data 2>/dev/null || \
        echo -e "${RED}Note: could not chown ./data — run 'sudo chown -R 1000:1000 data' before starting Docker.${NC}"
fi
echo ""

read -r -p "Do you want to start the Docker container now? (y/N): " start_docker
if [[ "$start_docker" =~ ^[Yy]$ ]]; then
    echo -e "${BLUE}Starting Docker containers on Port $PORT...${NC}"
    docker compose up -d --build
    echo -e "${GREEN}App is now running! Visit http://localhost:$PORT${NC}"
    if [ -z "$ADMIN_PASS" ]; then
        echo -e "${BLUE}No admin password was set — find the generated one with:${NC}"
        echo -e "${BLUE}    docker compose logs app | grep -A2 'GENERATED'${NC}"
    fi
else
    echo -e "${BLUE}Setup finished. You can start the app later using 'docker compose up -d'${NC}"
fi
